-- =====================================================================
-- LIFEQUEST SUPABASE SCHEMA (EDGE READY)
-- =====================================================================

-- 1. Profiles Table (Linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    avatar_url TEXT,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    exp INTEGER NOT NULL DEFAULT 0,
    gold INTEGER NOT NULL DEFAULT 0,
    intelligence INTEGER NOT NULL DEFAULT 0,
    strength INTEGER NOT NULL DEFAULT 0,
    stamina INTEGER NOT NULL DEFAULT 0,
    agility INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Achievements Table
CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    icon_path TEXT,
    exp_reward INTEGER NOT NULL DEFAULT 0,
    gold_reward INTEGER NOT NULL DEFAULT 0,
    rarity TEXT DEFAULT 'common' CHECK (rarity IN ('common', 'rare', 'epic', 'legendary')),
    condition JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Quests Table
CREATE TABLE IF NOT EXISTS public.quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
    frequency TEXT NOT NULL CHECK (frequency IN ('once', 'daily', 'weekly')),
    exp_reward INTEGER NOT NULL DEFAULT 10,
    gold_reward INTEGER NOT NULL DEFAULT 5,
    stat_reward_type TEXT CHECK (stat_reward_type IN ('intelligence', 'strength', 'stamina', 'agility', NULL)),
    stat_reward_value INTEGER NOT NULL DEFAULT 0,
    creator_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    is_admin_quest BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    achievement_id BIGINT REFERENCES public.achievements(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Quest Logs Table
CREATE TABLE IF NOT EXISTS public.quest_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    quest_id BIGINT NOT NULL REFERENCES public.quests(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'pending_review', 'completed', 'rejected')),
    submission_file_path TEXT,
    submission_notes TEXT,
    admin_notes TEXT,
    date DATE DEFAULT CURRENT_DATE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. User Achievements Table (Pivot)
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    achievement_id BIGINT NOT NULL REFERENCES public.achievements(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, achievement_id)
);

-- =====================================================================
-- TRIGGERS: AUTO CREATE PROFILE ON SIGNUP
-- =====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, avatar_url, is_admin)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', NULL),
    COALESCE((NEW.raw_user_meta_data->>'is_admin')::boolean, FALSE)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quest_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;

-- Profiles: Anyone authenticated can read all profiles (for leaderboard), update only their own
CREATE POLICY "Profiles are viewable by authenticated users" 
ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Quests: Public or authenticated can view active admin quests or personal quests
CREATE POLICY "Quests are viewable" 
ON public.quests FOR SELECT TO authenticated 
USING (is_admin_quest = true OR creator_id = auth.uid());

CREATE POLICY "Users can create personal quests" 
ON public.quests FOR INSERT TO authenticated 
WITH CHECK (is_admin_quest = false AND creator_id = auth.uid());

CREATE POLICY "Users can update personal quests" 
ON public.quests FOR UPDATE TO authenticated 
USING (creator_id = auth.uid());

CREATE POLICY "Users can delete personal quests" 
ON public.quests FOR DELETE TO authenticated 
USING (creator_id = auth.uid());

-- Quest Logs: Users can manage their own logs
CREATE POLICY "Users can view own quest logs" 
ON public.quest_logs FOR SELECT TO authenticated 
USING (user_id = auth.uid() OR (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);

CREATE POLICY "Users can insert own quest logs" 
ON public.quest_logs FOR INSERT TO authenticated 
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can update own quest logs" 
ON public.quest_logs FOR UPDATE TO authenticated 
USING (user_id = auth.uid() OR (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);

CREATE POLICY "Users can delete own quest logs" 
ON public.quest_logs FOR DELETE TO authenticated 
USING (user_id = auth.uid());

-- Achievements: Viewable by everyone authenticated
CREATE POLICY "Achievements are viewable" 
ON public.achievements FOR SELECT TO authenticated USING (true);

CREATE POLICY "User achievements viewable" 
ON public.user_achievements FOR SELECT TO authenticated USING (true);

-- Admin Override for Quests & Achievements
CREATE POLICY "Admins full access to quests" 
ON public.quests FOR ALL TO authenticated 
USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);

CREATE POLICY "Admins full access to achievements" 
ON public.achievements FOR ALL TO authenticated 
USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);

-- =====================================================================
-- STORAGE BUCKETS SETUP
-- =====================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('submissions', 'submissions', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies: allow authenticated users to upload submission proof and avatars
CREATE POLICY "Public read submissions" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'submissions');
CREATE POLICY "Authenticated upload submissions" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'submissions');

-- =====================================================================
-- SEED DATA: ACHIEVEMENTS & QUESTS
-- =====================================================================
INSERT INTO public.achievements (key_name, title, description, exp_reward, gold_reward, rarity, condition) VALUES
('first_quest_completed', 'Pejuang Hari Pertama', 'Selesaikan aktivitas (quest) pertamamu.', 50, 20, 'common', '{"type": "quest_completed", "count": 1}'),
('daily_10_streak', 'Rajin Harian', 'Selesaikan 10 quest harian secara berturut-turut.', 200, 100, 'rare', '{"type": "quest_streak", "frequency": "daily", "count": 10}'),
('quest_master_25', 'Petualang Sejati', 'Selesaikan 25 quest unik.', 500, 250, 'epic', '{"type": "quest_completed", "count": 25}'),
('intellect_1', 'Sang Intelektual (T1)', 'Capai total 50 poin Intelligence.', 200, 0, 'rare', '{"type": "stat_reached", "stat": "intelligence", "value": 50}'),
('strength_1', 'Binaragawan (T1)', 'Capai total 50 poin Strength.', 200, 0, 'rare', '{"type": "stat_reached", "stat": "strength", "value": 50}'),
('agility_1', 'Lincah Bagai Angin (T1)', 'Capai total 50 poin Agility.', 200, 0, 'rare', '{"type": "stat_reached", "stat": "agility", "value": 50}'),
('stamina_1', 'Tak Pernah Lelah (T1)', 'Capai total 50 poin Stamina.', 200, 0, 'rare', '{"type": "stat_reached", "stat": "stamina", "value": 50}')
ON CONFLICT (key_name) DO NOTHING;

INSERT INTO public.quests (title, description, difficulty, frequency, exp_reward, gold_reward, stat_reward_type, stat_reward_value, is_admin_quest, is_active, achievement_id) VALUES
('Mulai Perjalananmu', 'Selesaikan aktivitas positif pertamamu dan upload bukti di LifeQuest.', 'easy', 'once', 50, 20, NULL, 0, TRUE, TRUE, (SELECT id FROM public.achievements WHERE key_name = 'first_quest_completed' LIMIT 1)),
('Membaca Buku 30 Menit', 'Baca buku pengembangan diri atau ilmu pengetahuan minimal 30 menit.', 'easy', 'daily', 30, 15, 'intelligence', 2, TRUE, TRUE, NULL),
('Latihan Fisik (Push-up / Workout)', 'Lakukan olahraga ringan minimal 20 menit untuk menjaga stamina dan fisik.', 'medium', 'daily', 60, 25, 'strength', 3, TRUE, TRUE, NULL),
('Jogging / Lari Pagi', 'Lari pagi minimal 2 km di sekitar lingkungan atau treadmill.', 'medium', 'weekly', 120, 50, 'agility', 4, TRUE, TRUE, NULL),
('Meditasi & Refleksi Diri', 'Melakukan meditasi pernapasan 15 menit untuk ketenangan pikiran.', 'easy', 'daily', 25, 10, 'stamina', 2, TRUE, TRUE, NULL),
('Menyelesaikan Kursus Coding / Skill Baru', 'Tuntaskan satu modul atau proyek mini skill baru.', 'hard', 'weekly', 250, 100, 'intelligence', 5, TRUE, TRUE, NULL);

